In [1]:
# we can do all our usual Python right here
a = 1
b = 7.3
a/b # no need for 'print'

0.136986301369863

In [8]:
b*a # crtl-enter runs and stays in cell

7.3

In [3]:
a**b # shift-enter runs and adds a cell

1.0

In [10]:
print('hello') # by default ipynb uses '__repr__' instead of '__str__'

hello


In [11]:
# Numpy is really good for numerical analysis in Python
import numpy as np # this is conventional

In [32]:
# numpy offer a few additional data structures
# array-range (arange)
n = np.arange(3,10)
# an arange can only contain the SAME data types
# arange is a mutable indexed collection of ONE data type
n
n.dtype # these are int32
n

array([3, 4, 5, 6, 7, 8, 9])

In [30]:
# we can use n-dimensional arrays: (mutable of one type)
d = np.random.randn(9,3) # rows columns
d.dtype # float
d.shape # 9 by 3
d

array([[-0.94500363,  1.42758393,  0.25573185],
       [ 0.306648  ,  0.58734406,  0.2583767 ],
       [-0.67135944,  1.20755643, -1.00868353],
       [ 0.83342476,  1.9058618 , -1.86103146],
       [ 0.03981026,  1.3420358 , -0.09123645],
       [-1.50427056, -1.29687203, -0.77106732],
       [-0.01470666,  0.53907411,  0.73360731],
       [ 0.05234443, -0.82784377,  1.37108855],
       [ 0.27822993,  0.76660202,  2.12173326]])

In [33]:
e = np.random.randn(9, 3, 2) 
e.shape

(9, 3, 2)

### Creating Arrays

In [41]:
f = np.empty( (6,3) ) # floating point's if the memory is not actually 'empty'
f

array([[1.37962049e-306, 1.24610791e-306, 1.11260959e-306],
       [1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
       [1.78019082e-306, 4.45061456e-308, 1.24612081e-306],
       [1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
       [1.78019625e-306, 1.11255866e-306, 8.90098127e-307],
       [9.34609790e-307, 3.91792279e-317, 1.69121095e-306]])

In [43]:
g = np.zeros( (6,3) ) # these are floating point zeros
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# we can convert the type
s = d.astype(np.str_) # this is numpy syntax
# s = d.astype(np.string_) # we get bytes
s # we see the full accuracy of the original numerical values

array([['-0.9450036278533502', '1.4275839342969499',
        '0.2557318503733136'],
       ['0.3066479968130693', '0.5873440593862456',
        '0.25837670479312314'],
       ['-0.6713594403172901', '1.2075564263095584',
        '-1.008683530619453'],
       ['0.8334247600122415', '1.9058617979242434',
        '-1.8610314641141632'],
       ['0.03981025700638125', '1.3420357977515296',
        '-0.09123645188299816'],
       ['-1.5042705566759953', '-1.2968720273468595',
        '-0.7710673234750863'],
       ['-0.014706664878413588', '0.5390741052415022',
        '0.7336073053329419'],
       ['0.05234442500924299', '-0.827843769714676',
        '1.3710885481066302'],
       ['0.27822993094655646', '0.7666020182813867',
        '2.1217332591863656']], dtype='<U32')

In [48]:
# we can apply calculations to arrays
z = np.zeros( (3,3,3) )
z+3 # takes next to no time
(z+3)**2

array([[[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]],

       [[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]],

       [[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]]])

In [50]:
((d-2)*0.5)/b**100

array([[-6.85125018e-87, -1.33166752e-87, -4.05786171e-87],
       [-3.93941050e-87, -3.28639978e-87, -4.05170873e-87],
       [-6.21464492e-87, -1.84353905e-87, -6.99939497e-87],
       [-2.71391816e-87, -2.19002913e-88, -8.98229539e-87],
       [-4.56018125e-87, -1.53068652e-87, -4.86504804e-87],
       [-8.15232757e-87, -7.66983608e-87, -6.44660513e-87],
       [-4.68700930e-87, -3.39869490e-87, -2.94613327e-87],
       [-4.53102179e-87, -6.57868973e-87, -1.46309826e-87],
       [-4.00552223e-87, -2.86937444e-87,  2.83199995e-88]])

### Accessing Members from Arrays

In [53]:
d

array([[-0.94500363,  1.42758393,  0.25573185],
       [ 0.306648  ,  0.58734406,  0.2583767 ],
       [-0.67135944,  1.20755643, -1.00868353],
       [ 0.83342476,  1.9058618 , -1.86103146],
       [ 0.03981026,  1.3420358 , -0.09123645],
       [-1.50427056, -1.29687203, -0.77106732],
       [-0.01470666,  0.53907411,  0.73360731],
       [ 0.05234443, -0.82784377,  1.37108855],
       [ 0.27822993,  0.76660202,  2.12173326]])

In [56]:
d[1:6:2] # start:stop-before:step

array([[ 0.306648  ,  0.58734406,  0.2583767 ],
       [ 0.83342476,  1.9058618 , -1.86103146],
       [-1.50427056, -1.29687203, -0.77106732]])

In [57]:
# we can transpose an array
d.T

array([[-0.94500363,  0.306648  , -0.67135944,  0.83342476,  0.03981026,
        -1.50427056, -0.01470666,  0.05234443,  0.27822993],
       [ 1.42758393,  0.58734406,  1.20755643,  1.9058618 ,  1.3420358 ,
        -1.29687203,  0.53907411, -0.82784377,  0.76660202],
       [ 0.25573185,  0.2583767 , -1.00868353, -1.86103146, -0.09123645,
        -0.77106732,  0.73360731,  1.37108855,  2.12173326]])

In [58]:
# NB most operations do NOT alter the original structure
d

array([[-0.94500363,  1.42758393,  0.25573185],
       [ 0.306648  ,  0.58734406,  0.2583767 ],
       [-0.67135944,  1.20755643, -1.00868353],
       [ 0.83342476,  1.9058618 , -1.86103146],
       [ 0.03981026,  1.3420358 , -0.09123645],
       [-1.50427056, -1.29687203, -0.77106732],
       [-0.01470666,  0.53907411,  0.73360731],
       [ 0.05234443, -0.82784377,  1.37108855],
       [ 0.27822993,  0.76660202,  2.12173326]])